version: '3.8'

services:
  accesos-ms:
    container_name: redec-accesos-ms
    build: #build serve para criar a imagem do container a partir do Dockerfile (empacota apenas o java e o jar do projeto)
      context: .
      dockerfile: Dockerfile
    ports:
      # Lendo a porta do arquivo .env.dev
      - "${PORTA_APP}:${PORTA_APP}"
    environment:
      # Lendo o profile do arquivo .env.dev
      - SPRING_PROFILES_ACTIVE=${PROFILE_ATIVO}
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    env_file:
      - .env.dev
    depends_on:
      - rabbitmq
      - mysql #garante que o banco suba antes da aplicacao

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: redec-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Porta do protocolo AMQP (para o Java enviar mensagens)
      - "15672:15672" # Porta da Interface Gráfica (para nós gerenciarmos as filas)
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
        - "${MYSQL_PORT}:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - .env.dev
